# Generated by Django 5.0.7 on 2025-06-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SentimentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_text', models.TextField(help_text='Teks yang dianalisis')),
                ('tokenized_words', models.TextField(blank=True, help_text='Token hasil tokenisasi, dipisah koma')),
                ('matched_words', models.TextField(blank=True, help_text='Kata yang cocok dengan leksikon beserta bobotnya')),
                ('total_score', models.FloatField(help_text='Skor total dari hasil analisis')),
                ('sentiment_label', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
