# Generated by Django 5.0.7 on 2025-05-23 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('hour', models.IntegerField(default=12)),
                ('location', models.CharField(default='Unknown', max_length=100)),
                ('temperature', models.FloatField()),
                ('weather', models.CharField(default='clear', max_length=50)),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
            ],
        ),
    ]
