# Generated by Django 5.0.7 on 2025-05-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherrecord',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='weatherrecord',
            name='weather',
            field=models.CharField(max_length=50),
        ),
    ]
