# Generated by Django 5.0.7 on 2025-05-23 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_weatherrecord_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherrecord',
            old_name='weather',
            new_name='cuaca',
        ),
    ]
