# Generated by Django 5.0.7 on 2025-05-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathgame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mathgamescore',
            name='level',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='mathgamescore',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mathgamescore',
            name='total_questions',
            field=models.IntegerField(),
        ),
    ]
