# Generated by Django 5.0.7 on 2025-08-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('what', models.TextField()),
                ('who', models.CharField(max_length=255)),
                ('when', models.CharField(max_length=255)),
                ('where', models.CharField(max_length=255)),
                ('why', models.TextField()),
                ('how', models.TextField()),
                ('generated_content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/')),
            ],
        ),
    ]
