# Generated by Django 5.0.7 on 2025-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_generator', '0002_newsarticle_creator_newsarticle_editor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='diterbitkan_pada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
