# Generated by Django 5.0.7 on 2025-08-15 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_generator', '0003_newsarticle_diterbitkan_pada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='when',
            field=models.DateField(blank=True, null=True),
        ),
    ]
